-- CreateEnum
CREATE TYPE "ActivityAction" AS ENUM (
  'PROJECT_CREATED',
  'PROJECT_UPDATED',
  'PROJECT_ARCHIVED',
  'PROJECT_UNARCHIVED',
  'PROJECT_DELETED',
  'MEMBER_ADDED',
  'MEMBER_REMOVED',
  'TASK_CREATED',
  'TASK_UPDATED',
  'TASK_STATUS_CHANGED',
  'TASK_DELETED',
  'COMMENT_CREATED',
  'COMMENT_DELETED',
  'ATTACHMENT_UPLOADED',
  'ATTACHMENT_DELETED'
);

-- AlterTable
ALTER TABLE "Activity" ALTER COLUMN "action" TYPE "ActivityAction" USING ("action"::"ActivityAction");
